theme = "hugo-assembly"
baseURL = "https://opencollaboration.network"
languageCode = "en-US"
title = "Open Collaboration Networks"

# Metadata
[params]
  author = "Roberto Valenti"
  description = "Crazy guy"
  
  ContractAddress = "0x2af51b0d6ce37089D50FeC29Fd1A7DE21076C2f7"

# banner section (from here on is for assembly theme)
[params.banner]
  title = "Welcome to the collaborative world"
  byline = "A world were competition is trumped by openness"

[params.actions] # CTAs
  enable = true
  register = "Join the collective!"
  action ="https://forum.opencollaboration.network"

# Navigation section
[params.nav]
  home = "Home"
  welcome = "The Network"
  services = "Values"
  rules = "Collaboration Rules"
  collective = "Open Collective"
  contact = "Contact Us"

  # Welcome section
[params.welcome]
  enable = true
  title = "About the Network"

  subtitle = "We believe that companies should not exist to simply maximize profits, but to serve the needs of the local and global community."
  description = "We aim to realign the incentives of producers and consumers in order to develop a more inclusive, open and regenerative form of production. This is achieved by openly sharing information about the needs of the users, and the processes of the producers. The consumer will be able to choose matching producers, while the producers will implement measures in order to satisfy the user’s needs."
  button_text = "Join us"
  button_link = "https://forum.opencollaboration.network"

# Services section
[params.services]
  enable = true
  title = "Network Values"

  [[params.services.item]]
    weight = "A"
    description = "Our members join together to openly and collectively improve the social, economic and ecosystem targets that strive for wellbeing."
    title = "Purpose Driven"

  [[params.services.item]]
    weight = "B"
    description = "A consumer’s informed choice affects the producers decisions.  We all share the responsibility to build the society and ecosystem we want everytime we decide what to buy, and from whom."    
    title = "Consumer's Choice"

  [[params.services.item]]
    weight = "C"
    description = "We commit to share information to allow an open production planning and open optimization of processes: we openly share the sales and production information as required by the consumer"
    title = "Open Data"

  [[params.services.item]]
    weight = "A"
    description = "Producers commit to satisfy the consumer needs, while consumers  commit to make an informed choice over which produce to acquire."
    title = "Co-production"

  [[params.services.item]]
    weight = "B"
    description = "Any producers and consumers can submit proposals for improvement, members can vote with their transactions."
    title = "Distributed Governance"

[[params.services.item]]
    weight = "C"
    description = "We adopt mechanisms for open and peer-to-peer validation of credibility for all the shared information. "
    title = "Auditable"


[params.forum]
  enable = false

[params.rules]
  enable = true

[params.collective]
  enable = true

[params.contribute]
  enable = true

# Contact section
[params.contact]
  enable = false
  title = "Apply to be a member "
  message = "Everone is welcome. "
  name_placeholder = "Your name" 
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  copy = "2018 &copy; Assembly Inc. | All rights reserved"
  twitter = ""
  facebook = ""
  instagram = ""

